# Generated by Django 6.0.4 on 2026-04-22 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_company_cnpj'),
        ('manifest', '0001_initial'),
        ('vehicle', '0004_alter_fuelconsumptionlog_manifest_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ManifestModel',
            new_name='Manifest',
        ),
    ]
