# Generated by Django 6.0.4 on 2026-04-21 20:17

import apps.driver.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='cnh',
            field=apps.driver.models.CnhField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='cpf',
            field=apps.driver.models.CpfField(max_length=20, unique=True),
        ),
    ]
