# Generated by Django 6.0.4 on 2026-04-21 20:58

import apps.driver.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0002_alter_driver_cnh_alter_driver_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='cnh',
            field=apps.driver.models.CnhField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
