# Generated by Django 6.0.4 on 2026-04-21 21:06

import apps.driver.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0003_alter_driver_cnh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='cpf',
            field=apps.driver.models.CpfField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
