# Generated by Django 6.0.4 on 2026-04-21 20:17

import apps.vehicle.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tractorunitmodel',
            name='license_plate',
            field=apps.vehicle.models.LicensePlateField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='trailermodel',
            name='license_plate',
            field=apps.vehicle.models.LicensePlateField(max_length=20, unique=True),
        ),
    ]
