# Generated by Django 6.0.4 on 2026-04-21 22:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_company_cnpj'),
        ('vehicle', '0002_alter_tractorunitmodel_license_plate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fuelconsumptionlog',
            name='company',
        ),
        migrations.AlterField(
            model_name='fuelconsumptionlog',
            name='load_status',
            field=models.CharField(choices=[('LOADED', 'Loaded'), ('EMPTY', 'Empty'), ('LOADED_THEN_EMPTY', 'Loaded/Empty'), ('EMPTY_THEN_LOADED', 'Empty/Loaded')], max_length=20),
        ),
        migrations.AlterField(
            model_name='fuelconsumptionlog',
            name='tractor_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuel_logs', to='vehicle.tractorunitmodel'),
        ),
        migrations.CreateModel(
            name='ManifestModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id_external', models.CharField(blank=True, max_length=120, null=True)),
                ('origin', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manifests', to='company.company')),
            ],
        ),
        migrations.AddField(
            model_name='fuelconsumptionlog',
            name='manifest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuel_logs', to='vehicle.manifestmodel'),
        ),
    ]
