# Generated by Django 6.0.4 on 2026-04-22 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manifest', '0001_initial'),
        ('vehicle', '0003_remove_fuelconsumptionlog_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelconsumptionlog',
            name='manifest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuel_logs', to='manifest.manifestmodel'),
        ),
        migrations.AlterField(
            model_name='fuelconsumptionlog',
            name='load_status',
            field=models.CharField(choices=[('LOADED', 'C'), ('EMPTY', 'V'), ('LOADED_THEN_EMPTY', 'C/V'), ('EMPTY_THEN_LOADED', 'V/C')], max_length=20),
        ),
        migrations.DeleteModel(
            name='ManifestModel',
        ),
    ]
