# Generated by Django 6.0.4 on 2026-04-21 20:17

import apps.company.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='cnpj',
            field=apps.company.models.CnpjField(max_length=20, unique=True),
        ),
    ]
